### PR TITLE
Adding Zedboard tutorial page

### PR DESCRIPTION
**Pull request by furkanturan**
Hello, I created a page that explains working with Zedboard, as we talked before. Since make targets, or general structure didn't change much, I copied some parts from what you provided already, or gave links to them. I hope you find the explanation clear enough. 

I added a short sentence, and a footnote where I mentioned the name of my research group, since I am working on this for my project here.

Kind Regards, Furkan

### CODE REVIEW

**Comment by wsong83** [comment]
Many thanks Furkan. I am planing to have a try myself next week and then have it merged to debug-v0.3. So I will leave this PR open until the lowrisc-chip repo is merged.

**Comment by furkanturan** [comment]
Hello Wei, That's ok, thank you.

Just to inform you, while writing the tutorial I noticed that programming the board using Makefile didn't work in my first commit. I didn't noticed it before, as I was working with the GUI. I fixed the problems, and tested every make target. For me they are all working fine, and it is better to test yourself as well. I committed all the changes to my repository (the master branch). So please be sure to pull the latest commits.

**Comment by furkanturan** [comment]
Updated the PR according to the changes in the zedboard repo's Readme file.

Please feel free to play with title, if you have a better one in your mind; or with the place of the link to the page, if you think that there is a better place for it.

**Comment by wsong83** [comment]
Thanks Furkan!

**Pull request merged**
