### PR TITLE
minion-v0.4: s/filing system/file system/

### PR DESCRIPTION
**Pull request by neuschaefer**
Replace the term "filing system" with the much more common term "file system".

### CODE REVIEW

**Comment by jrrk** [comment]
Filing is the present continuous
tense of the verb 'to file something
In the system'. I don't think your
suggestion helps the grammar at all.

**Comment by wsong83** [comment]
Hi Jonathan,
I think the argument is not about grammar. I am not in a position to argue about English grammar anyway.
However, as a non-native speaker, I share the similar feeling with @neuschaefer 
A quick search of both terms in scholar.google, "filing system" turns out around 2.4 million times, while "file system" turns out 5.2 million times, more than doubled.
I would suggest here is a trade-off between what is believed the most correct way of expression and what is the considered the most common expression.

**Comment by neuschaefer** [comment]
@jrrk: I agree that "filing system" makes sense grammatically (note that I'm also a non-native speaker), but in computing, I've never heard this term. The [english Wikipedia article about "filing system"](https://en.wikipedia.org/wiki/Filing_system) is a disambiguation that redirects to the pages [File system](https://en.wikipedia.org/wiki/File_system), and [Filing cabinet](https://en.wikipedia.org/wiki/Filing_cabinet), which seems to be a piece of furniture where you *file* paper.

My argument isn't that "filing system" is completely wrong, but it's an uncommon-enough term to unnecessarily confuse people a little bit.

Grammatically, you can understand a "file system" as a system of files, or a system to manage and store files.

**Comment by jrrk** [comment]
It's no big deal for me. In British English a filing system carries the 
implication that filing is currently

going on, whereas the American dialect file system implies it was 
created some time ago.

So if you are pedantic like me, you would use file system for mount -o 
ro and filing system for mount -o rw.

But what matters is trying to be clear for the majority of non-native 
speakers, so I am happy to go with the flow,

and thanks for taking the time to prepare this patch.

**Comment by neuschaefer** [comment]
Thank you for this detailed explanation.

**Pull request merged**
